apiVersion: v1                # Specifies the API version
kind: Service                 # Indicates the type of Kubernetes object being created
metadata:
  name: passapp-service      # The name of the Service
spec:
  selector:
    app: passapp             # The Service will route traffic to Pods labeled with 'app: pass_app'
  ports:
    - protocol: TCP           # The protocol used
      port: 80                # The port on which the Service will be exposed
      targetPort: 5000        # The port on the Pod that will receive the traffic
  type: NodePort              # The Service will be exposed on each Node’s IP at a static port (the NodePort)
